### ISSUE TITLE
Can't find the Commandlet on Linux.

### ISSUE THREAD

**Issue by Zerophase** [ue4plugins/CommandletPlugin#2]
The engine keeps crashing whenever I try to run the HelloWorld commandlet at startup.
I'm on engine version 4.15.3.

Running `UE4Editor ~/Documents/unrealprojects/CommandletExample/Binaries/Linux/CommandletExample -run=HelloWorldCommandlet`

Always gives:

> [2017.05.24-02.36.14:821][  0]LogInit:Error: HelloWorldCommandlet looked like a commandlet, but we could not find the class.

just running `~/Documents/unrealprojects/CommandletExample/Binaries/Linux/CommandletExample -run=HelloWorldCommandlet`

Gives:

> LogLinux:Error: appError called: Assertion failed: Assertion failed: HasFoundDataDirectory [File:/opt/unreal-engine/Engine/Source/Runtime/Core/Private/Internationalization/ICUInternationalization.cpp] [Line: 128]
> ICU data directory was not discovered:
> ../../../CommandletExample/Content/Internationalization
> ../../../Engine/Content/Internationalization
> 
> Signal 11 caught.
> Malloc Size=131076 LargeMemoryPoolOffset=131092

**Comment by gmpreussner** [comment]
try this:
`UE4Editor ~/Documents/unrealprojects/CommandletExample/Binaries/Linux/CommandletExample -run=HelloWorld`

**Comment by Zerophase** [comment]
No dice. It looks like there is a bug in Unreal causing issue with Commandlets on Linux. https://answers.unrealengine.com/questions/91089/cant-run-packaged-game-on-linux-machine.html

**Comment by gmpreussner** [comment]
what is the error when you type my command line? Make sure that the parameter to '-run=' is _HelloWorld_, not _HelloWorldCommandlet_.

**Comment by gmpreussner** [comment]
Closing this out due to lack of response.
